os:
  - linux

dist: bionic

git:
  depth: 5

# We use cpp for unit tests, and c for the main project.
language: cpp
compiler: clang

env:
#  - PUBLISHMETA=True
#  - PUBLISHDOCS=True
# Specify the main Mafile supported goals.
  - GOAL=SPRF3
#  - GOAL=all
#  - GOAL=AFROMINI
#  - GOAL=AIORACERF3
#  - GOAL=...
# Or specify targets to run.
#  - TARGET=AFROMINI
#  - TARGET=AIORACERF3
#  - TARGET=...

addons:
  apt:
    update: true
    packages:
    - clang-10
    - lcov
    - libc6-i386
    - libblocksruntime-dev

before_install:
  - |
    echo "Target branch: $TRAVIS_BRANCH"
    echo "Commit range: $TRAVIS_COMMIT_RANGE"
    if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      COMMIT_RANGE="$TRAVIS_BRANCH"
    else
      COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    fi
    FILE_LIST=$(git diff --name-only $COMMIT_RANGE)
    echo "$FILE_LIST" | grep -qvE '(\.md$)|(^(docs|support))/' || {
      echo "Only files not used in the build process were updated, aborting."
      exit
    }
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov

install:
  - make arm_sdk_install

before_script:
  - make arm_sdk_version

script: ./.travis.sh

cache:
  timeout: 1000
  directories:
  - downloads
  - tools
