#pragma once

// PID Defaults for SPRF3 Target (derived from existing hardcoded values)

#define SPRF3_PID_ROLL  { 42, 85, 35, 90 }
#define SPRF3_PID_PITCH { 46, 90, 38, 95 }
#define SPRF3_PID_YAW   { 45, 90, 0,  90 }
#define SPRF3_PID_LEVEL { 50, 50, 75, 0 }
#define SPRF3_PID_MAG   { 40, 0,  0,  0 }

#define SPRF3_PIDSUM_LIMIT      500
#define SPRF3_PIDSUM_LIMIT_YAW  400

#define SPRF3_YAW_LOWPASS_HZ    0
#define SPRF3_DTERM_NOTCH_HZ    0
#define SPRF3_DTERM_NOTCH_CUTOFF 0

#define SPRF3_ITERM_WINDUP_POINT_PERCENT 100
#define SPRF3_VBAT_PID_COMPENSATION 0
#define SPRF3_PID_AT_MIN_THROTTLE PID_STABILISATION_ON
#define SPRF3_LEVEL_ANGLE_LIMIT 55
#define SPRF3_FEEDFORWARD_TRANSITION 0
#define SPRF3_YAW_RATE_ACCEL_LIMIT 0
#define SPRF3_RATE_ACCEL_LIMIT 0
#define SPRF3_ITERM_THROTTLE_THRESHOLD 250
#define SPRF3_ITERM_ACCELERATOR_GAIN 3500

#define SPRF3_CRASH_TIME 500
#define SPRF3_CRASH_DELAY 0
#define SPRF3_CRASH_RECOVERY_ANGLE 10
#define SPRF3_CRASH_RECOVERY_RATE 100
#define SPRF3_CRASH_DTHRESHOLD 50
#define SPRF3_CRASH_GTHRESHOLD 400
#define SPRF3_CRASH_SETPOINT_THRESHOLD 350
#define SPRF3_CRASH_RECOVERY PID_CRASH_RECOVERY_OFF
#define SPRF3_CRASH_LIMIT_YAW 200

#define SPRF3_HORIZON_TILT_EFFECT 75
#define SPRF3_HORIZON_TILT_EXPERT_MODE false

#define SPRF3_ITERM_LIMIT 400
#define SPRF3_THROTTLE_BOOST 5
#define SPRF3_THROTTLE_BOOST_CUTOFF 15
#define SPRF3_ITERM_ROTATION false
#define SPRF3_ITERM_RELAX ITERM_RELAX_RP
#define SPRF3_ITERM_RELAX_CUTOFF ITERM_RELAX_CUTOFF_DEFAULT
#define SPRF3_ITERM_RELAX_TYPE ITERM_RELAX_SETPOINT

#define SPRF3_ACRO_TRAINER_ANGLE_LIMIT 20
#define SPRF3_ACRO_TRAINER_LOOKAHEAD_MS 50
#define SPRF3_ACRO_TRAINER_DEBUG_AXIS FD_ROLL
#define SPRF3_ACRO_TRAINER_GAIN 75

#define SPRF3_ABS_CONTROL_GAIN 0
#define SPRF3_ABS_CONTROL_LIMIT 90
#define SPRF3_ABS_CONTROL_ERROR_LIMIT 20
#define SPRF3_ABS_CONTROL_CUTOFF 11

#define SPRF3_ANTI_GRAVITY_MODE ANTI_GRAVITY_SMOOTH

#define SPRF3_DTERM_LOWPASS_HZ 150
#define SPRF3_DTERM_LOWPASS2_HZ 150
#define SPRF3_DTERM_FILTER_TYPE FILTER_PT1
#define SPRF3_DTERM_FILTER2_TYPE FILTER_PT1
#define SPRF3_DYN_LPF_DTERM_MIN_HZ 70
#define SPRF3_DYN_LPF_DTERM_MAX_HZ 170

#define SPRF3_LAUNCH_CONTROL_MODE LAUNCH_CONTROL_MODE_NORMAL
#define SPRF3_LAUNCH_CONTROL_THROTTLE_PERCENT 20
#define SPRF3_LAUNCH_CONTROL_ANGLE_LIMIT 0
#define SPRF3_LAUNCH_CONTROL_GAIN 40
#define SPRF3_LAUNCH_CONTROL_ALLOW_TRIGGER_RESET true

#define SPRF3_USE_INTEGRATED_YAW false
#define SPRF3_INTEGRATED_YAW_RELAX 200
#define SPRF3_THRUST_LINEARIZATION 0

#define SPRF3_D_MIN { 23, 25, 0 }
#define SPRF3_D_MIN_GAIN 37
#define SPRF3_D_MIN_ADVANCE 20

#define SPRF3_MOTOR_OUTPUT_LIMIT 100
#define SPRF3_AUTO_PROFILE_CELL_COUNT AUTO_PROFILE_CELL_COUNT_STAY
#define SPRF3_TRANSIENT_THROTTLE_LIMIT 0

#define SPRF3_DYN_IDLE_MIN_RPM 0
#define SPRF3_DYN_IDLE_P_GAIN 50
#define SPRF3_DYN_IDLE_I_GAIN 50
#define SPRF3_DYN_IDLE_D_GAIN 50
#define SPRF3_DYN_IDLE_MAX_INCREASE 150

#define SPRF3_FEEDFORWARD_AVERAGING FEEDFORWARD_AVERAGING_OFF
#define SPRF3_FEEDFORWARD_MAX_RATE_LIMIT 100
#define SPRF3_FEEDFORWARD_JITTER_FACTOR 60
#define SPRF3_FEEDFORWARD_SMOOTH_FACTOR 37
#define SPRF3_FEEDFORWARD_BOOST 15

#define SPRF3_DYN_LPF_CURVE_EXPO 5
#define SPRF3_LEVEL_RACE_MODE false
#define SPRF3_VBAT_SAG_COMPENSATION 0
